"""create new model

Revision ID: 432d12250fc9
Revises: a752b2ac9429
Create Date: 2021-11-17 22:15:53.063230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '432d12250fc9'
down_revision = 'a752b2ac9429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch_report_statuses', sa.Column('is_debate', sa.Boolean(), nullable=True))
    op.add_column('branch_report_statuses', sa.Column('branch_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'branch_report_statuses', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'branch_report_statuses', type_='foreignkey')
    op.drop_column('branch_report_statuses', 'branch_id')
    op.drop_column('branch_report_statuses', 'is_debate')
    # ### end Alembic commands ###
