"""empty message

Revision ID: 52fa5e1bf98b
Revises: 6e8a4713bcc0
Create Date: 2021-11-05 01:38:35.924793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52fa5e1bf98b'
down_revision = '6e8a4713bcc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_name', sa.String(length=30), nullable=False),
    sa.Column('login_name', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_name'),
    sa.UniqueConstraint('login_name')
    )
    op.create_table('dairy_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('in_party', sa.Integer(), nullable=True),
    sa.Column('out_party', sa.Integer(), nullable=True),
    sa.Column('readed', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('is_debate', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('dairy_report')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dairy_report',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('in_party', sa.INTEGER(), nullable=True),
    sa.Column('out_party', sa.INTEGER(), nullable=True),
    sa.Column('readed', sa.INTEGER(), nullable=True),
    sa.Column('is_debate', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('dairy_reports')
    op.drop_table('branches')
    # ### end Alembic commands ###
