"""update database

Revision ID: 6e8a4713bcc0
Revises: a548a9c50239
Create Date: 2021-11-04 21:24:55.624010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e8a4713bcc0'
down_revision = 'a548a9c50239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dairy_report', sa.Column('in_party', sa.Integer(), nullable=True))
    op.add_column('dairy_report', sa.Column('out_party', sa.Integer(), nullable=True))
    op.add_column('dairy_report', sa.Column('readed', sa.Integer(), nullable=True))
    op.add_column('dairy_report', sa.Column('is_debate', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dairy_report', 'is_debate')
    op.drop_column('dairy_report', 'readed')
    op.drop_column('dairy_report', 'out_party')
    op.drop_column('dairy_report', 'in_party')
    # ### end Alembic commands ###
