"""add comment

Revision ID: d1dc73fa8566
Revises: e232f31bfbf6
Create Date: 2021-11-24 00:12:15.466443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1dc73fa8566'
down_revision = 'e232f31bfbf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dairy_reports', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dairy_reports', 'comment')
    # ### end Alembic commands ###
