"""create new db

Revision ID: e232f31bfbf6
Revises: 
Create Date: 2021-11-23 01:11:12.697438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e232f31bfbf6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_name', sa.String(length=30), nullable=False),
    sa.Column('login_name', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('is_commissioner', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_name'),
    sa.UniqueConstraint('login_name')
    )
    op.create_table('branch_report_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_debate', sa.Boolean(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('branch_report_totals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('in_party', sa.Integer(), nullable=True),
    sa.Column('out_party', sa.Integer(), nullable=True),
    sa.Column('standing', sa.Integer(), nullable=True),
    sa.Column('leaf_m', sa.Integer(), nullable=True),
    sa.Column('leaf_a', sa.Integer(), nullable=True),
    sa.Column('dialogue', sa.Integer(), nullable=True),
    sa.Column('support', sa.Integer(), nullable=True),
    sa.Column('workon_join', sa.Integer(), nullable=True),
    sa.Column('join', sa.Integer(), nullable=True),
    sa.Column('akahata_h', sa.Integer(), nullable=True),
    sa.Column('akahata_n', sa.Integer(), nullable=True),
    sa.Column('support_member', sa.Integer(), nullable=True),
    sa.Column('ask_favor', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dairy_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('in_party', sa.Integer(), nullable=True),
    sa.Column('out_party', sa.Integer(), nullable=True),
    sa.Column('standing', sa.Integer(), nullable=True),
    sa.Column('leaf_m', sa.Integer(), nullable=True),
    sa.Column('leaf_a', sa.Integer(), nullable=True),
    sa.Column('dialogue', sa.Integer(), nullable=True),
    sa.Column('support', sa.Integer(), nullable=True),
    sa.Column('workon_join', sa.Integer(), nullable=True),
    sa.Column('join', sa.Integer(), nullable=True),
    sa.Column('akahata_h', sa.Integer(), nullable=True),
    sa.Column('akahata_n', sa.Integer(), nullable=True),
    sa.Column('support_member', sa.Integer(), nullable=True),
    sa.Column('ask_favor', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dairy_reports')
    op.drop_table('branch_report_totals')
    op.drop_table('branch_report_statuses')
    op.drop_table('branches')
    # ### end Alembic commands ###
